#!/usr/bin/env node

var builder = require('./builder');

var templateData = {
  version: '0.10.0'
};

var baseDir = __dirname + '/..',
    sourceDir = baseDir + '/src',
    outputDir = baseDir + '/distribution';

//Files to concatenate into main file
var fileList = [
  'form.js',
  'helpers.js',
  'validators.js',
  'field.js',
  'editors.js',
  'setup.js',
  'templates/default.js'
];

//Concatenate the main files
var mainContents = builder()
  .setDir(sourceDir)
  .concat(fileList)
  .getContent();

//Save regular dev and mini versions
builder()
  .setDir(baseDir)
  .setContent(mainContents)
  .wrap('scripts/build-templates/main.js', templateData)
  .save('distribution/backbone-forms.js')
  .uglify()
  .save('distribution/backbone-forms.min.js');


//Main AMD file (for RequireJS)
builder()
  .setDir(baseDir)
  .setContent(mainContents)
  .wrap('scripts/build-templates/main.amd.js', templateData)
  .save('distribution/backbone-forms.amd.js')
  .uglify()
  .save('distribution/backbone-forms.amd.min.js');


//Templates
